spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: test_db
    password: 571632
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
